sudo: required

language: java

before_install:
- sudo apt-get install -y markdown

jdk:
- oraclejdk8

services:
- docker

before_deploy:
- mvn -DskipTests package
- export JAR_FILE=$(ls target/config-server-*.jar)
- echo "deploying $JAR_FILE to GitHub releases"
- export RELEASE_NOTES=$(awk -v start=1 '/^#{2}[[:space:]].*$/{n++;next};n==start;n==start+1{exit}' CHANGELOG.md | markdown | awk '{printf "%s",$0} END {print ""}')

deploy:
  - provider: script
    script: mvn -DskipTests package -Ddocker.username=$DOCKER_USER -Ddocker.password=$DOCKER_PASS docker:build docker:push
    on:
      tags: true
  - provider: releases
    api_key:
      secure: Ceo8Tu27sRPa9deCxccYMkEEcyVxsz5xF4PP/VmzPu4fnERgLtuPQqx76Wdge/EKywmFgzwSEvB/2FvuEhpOVvJ3CYdDJ3BaPdLB06J0tWEeMEe7ldCMAGyagVyyqZrwM3D8CXYMESw4wBbUZWdRezPtHo5Lcs6tssZLZrtdt9LMF7kAs1hrhGV4L16vRCuhdAAlYV/qObGMLKfftny08b5M7C/9bPcXqPRksmCqQC+ekOrWL3iQeZCnMJU2ktOsg1vYo3UsA7e+pT/qfuc0Og/p0c3+ZlFWYQmebhekQ6KJ+WZYXXJtBDVyfz6LXnNDwYqA9v3owNd12khpr8QgQkNUvhG2kNQGKF7gDfisI4/ULWz7dOOPwteGIyOk+nIO7e5Z7eZf0k0d8xOcQd7SdW2qGyRNMVuShqvt3I4vV5xbJhHsOquop8eg6G5Jgj/UwnsgzTrlXC3DCwo7d6ajMn/gn377bbk/eRkLBKPY2//E2L9aBE5U6StAJOtvvADFjcY3RwgeZ/tiob9VZJRcpi98d8mwTBKOC7jM+P4Kz8+xo2FNJV99L6KTiEMUkz8e/bjiurxcihjP7JyrL0eG1+IAkb/Tt0z1bTvw65JNxiwEifZWVMlM4MpG/TtZKGQi7gqqovYyJAtixxFl35rVbm7ZGgcovpTgOVADeFZyMtY=
    file: '${JAR_FILE}'
    body: "${RELEASE_NOTES}"
    skip_cleanup: true
    on:
      tags: true
      repo: coffeenet/coffeenet-config-server

env:
  global:
  - secure: MYB3jDGzGn6nXGODWOD4CaIoLelqoISi1YOCYetKRZrUFt2afK2UysNS0QU4EGJApdeV43rk2MWIwY0wH426sA59/OwL3bV0Zb6mniWyH6vGmJMpI9EEvOS4bvuqN+Mrp5Vj968WdJ3qQfVsULf6wPTworQZb7SPvW6+skn1xPbsVfvbJn+x1jyDjHUMuGAW7+FxuDoHPX0xl5qjnyGLKVDuTWySUJkFZD5JFhiX1M7ixtgncx4Sw0ULS7pjzFz1N3lXIUhSntwBRoE4x4NAqvL3TerN5n5rH0weObJtKAWddyS7EFR2MIKt7RVYly5Qfz8eFqHC4aBBFM6myax3AvUNEkp/L4xECBVBzIYkCmy1cui9rSLDZOEp3U/MX/APdRDDMXqs+AT3n5QVqtukpCdGOLtakVHPr7RnHVpV7iSSZ2GFlDCOevolBJf2D00PTty5y3Js8Erh0T6AsY2LRFERvR6r1A1Q29+D65XPP08uA2xD76wKSp5hseqjSQuvt+s5ezzwnlzXBsjfvLX9sQWVbM3nRMTESjf5r3A0GN2U6oBG7LeTEgzb58L6HyXJEUXzSE8Xqjyx0d9vGsX+MQ0+xmXc22XDTBZqPTpIoVrT+qnAL03AhjKNygwNik7OyUeFaCveL/gTI20MopbOrxgNABcKzJvBz8imagmLtp0=
  - secure: d+jVITuWngN8LKaeHsd4Qe3bJc8Skf/h3vVnaP34gSbvX4kuy1ZsNPGtctACxMXk/3M08t8/gfC0ZcD2VYdwV85YVNaUk/IxKiaUBgBqXAWUrlPHF0I8ultH/F5waqeIrAQQefNeX9MlmBF6gGQPE2fdKgDcK3eAvVcdj8Q1sU5VyeVpkv4PTdiSdf/pfTj4uwFy3BbIuopzGnS7qySJc/bTe0EOmoXKw62UGtmSgD2geSqsplCwh5M54yX7SOtRXMEFE5VXexfvyowzvxRake1oAa/+IecxAmMD6MEkPTXeRbQANkfv50vOItywLHKtDhzNiFm7IEr7thgZZVemXwUFVrAsfRqWcLhMazLbjPALsxEcqaYVa1ODCkfUGCsXZye99R51zDKidYNYQrlWHKmn9gSs6j+kbCERE1vP2I6TaiCt8+i5VOA7FQebVx76mX14Af21V1iro1O0XtmpfYjsdqliRELweAKDttqXgIYKIPSFMzIfTHb6NvuOiyCKl5UmTub3xbxal9kD7gnZmq6dv8LdOElBswMtlGUFIM0k/OL7cpodwvRYIb7CXfZiuNYjSQ80X4HWQY9K1zxTbpJYe+dhMl/glAnSaQyaVHRRM/5lzldRDvYdFM7BgM0YfpWiVo34D6SxZhvU34pG5S2UGg9S4jXNELUJAHXbTrM=

notifications:
  irc:
    channels:
      - "irc.synyx.de#CoffeeNet"
    on_success: change # default: always
    on_failure: always # default: always
    use_notice: true
    skip_join: true

cache:
  directories:
    - $HOME/.m2